version: '3'

services:
  app:
    image: node:latest
    tty: true
    stdin_open: true
    container_name: rentskins_backend_on
    working_dir: /src
    depends_on:
      - api-rentskins
    ports:
      - 3333:3333
    environment:
      - node=dev
      - url=postgresql://docker:docker@localhost:5432/apirentskins?schema=public
    volumes:
      - ./:/src

  api-rentskins:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apirentskins