 name: Continuos Integration

 on: [push]

 jobs:
   continuos-integration:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3
       - name: Using Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 18.x
           cache: 'npm'
       - name: run install, build and test
         run: |
           npm ci
           npm run test
        
         env:
            JWT_SECRET: test
            STEAM_USERNAME: test
            STEAM_PASSWORD: test
            STEAM_KEY: test
            STRIPE_PUBLIC_KEY: test
            STRIPE_SECRET_KEY: test
            STRIPE_SECRET_WEBHOOK_KEY: test
            MERCADO_SECRET_KEY: test     
        
        